PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX exv: <http://example.org/vocab#>
SELECT ?name ?start WHERE {
  {
    { ?event rdf:type exv:FoodFestival . }
    UNION
    { ?event rdf:type exv:MusicFestival . }
  	?event exv:name ?name .
  }
  OPTIONAL
  { ?event exv:start ?start . }
}